### ISSUE TITLE
Getting several errors on files

### ISSUE THREAD

**Issue by genyded** [nathantreid/meteor-react-toolbox-example#5]
Followed the instructions and getting the following - not sure if this issue should be here or against the css modules repo, but hope someone can help:

``````
=> Started proxy.
=> Started MongoDB.
[Error: File 'control' not found at any of the following paths: ["control","cont
rol.scss","control.sass","./_control","./_control.scss","./_control.sass"]]
[Error: File 'spinner' not found at any of the following paths: ["spinner","spin
ner.scss","spinner.sass","./_spinner","./_spinner.scss","./_spinner.sass"]]
[Error: File 'select' not found at any of the following paths: ["select","select
.scss","select.sass","./_select","./_select.scss","./_select.sass"]]
[Error: File 'mixins' not found at any of the following paths: ["mixins","mixins
.scss","mixins.sass","./_mixins","./_mixins.scss","./_mixins.sass"]]

TypeError: Cannot set property './components.scss.js' of undefined
    at ImportScanner._checkSourceAndTargetPaths (C:\tools\isobuild\import-scanne
r.js:256:7)
    at C:\tools\isobuild\import-scanner.js:159:12
    at Array.forEach (native)
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:158:11)
    at C:\tools\isobuild\compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:80
5:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:913:8)
    at C:\tools\isobuild\bundler.js:684:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:675:18)
    at C:\tools\isobuild\bundler.js:2474:14
    at C:\tools\isobuild\bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\genyd\AppData\Local\.meteor\packages\
meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\
underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2562:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2455:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12```
``````

**Comment by genyded** [comment]
In my copy and paste haste... i missed an @ on one of the imports... added it and all is peachy.
